function set_simpars(;BG_AGG_adj_factor=0.25,
                     BG_AGG_maxiter=100,
                     BG_epsilon=0.0000000001,
                     BG_MPK_maxiter=40,
                     perbeg=1900,
                     perend=2400,
                     DS_AGG_adjfactor=0.35,
                     DS_AGG_maxiter=100,
                     DS_ini_AGG=1,
                     beta_maxiter=35, 
                     beta_epsilon=0.01,
                     betaL=0.991,
                     betaH=1.0,
                     seedR1900L=[0.032;0.04],
                     seedR1900H=[0.02;0.026],
                     seedR2400L=[0.026;0.03],
                     seedR2400H=[0.014;0.021],
                     nper = length(1900.125:.25:2400),
                     num_periods=720,
                     per_sim_start=1900)
    simpars = simpars_t(BG_AGG_adj_factor,
                        BG_AGG_maxiter,
                        BG_epsilon,
                        BG_MPK_maxiter,
                        perbeg,
                        perend,
                        DS_AGG_adjfactor,
                        DS_AGG_maxiter,
                        DS_ini_AGG,
                        beta_maxiter,
                        beta_epsilon,
                        betaL,
                        betaH,
                        seedR1900L,
                        seedR1900H,
                        seedR2400L,
                        seedR2400H,
                        nper,
                        num_periods,
                        per_sim_start)
    return simpars
end
